
function pfb_core_config(this_block)

  % Revision History:
  %
  %   12-Dec-2013  (01:28 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /data1/dprice/leda512/bb/pfb_core.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('pfb_core');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('sync');
  this_block.addSimulinkInport('pol0');
  this_block.addSimulinkInport('pol1');
  this_block.addSimulinkInport('pol2');
  this_block.addSimulinkInport('pol3');
  this_block.addSimulinkInport('pol4');
  this_block.addSimulinkInport('pol5');
  this_block.addSimulinkInport('pol6');
  this_block.addSimulinkInport('pol7');
  
  this_block.addSimulinkOutport('sync_out');
  this_block.addSimulinkOutport('out_pol0');
  this_block.addSimulinkOutport('out_pol1');
  this_block.addSimulinkOutport('out_pol2');
  this_block.addSimulinkOutport('out_pol3');
  this_block.addSimulinkOutport('out_pol4');
  this_block.addSimulinkOutport('out_pol5');
  this_block.addSimulinkOutport('out_pol6');
  this_block.addSimulinkOutport('out_pol7');
  

  out_pol0_port = this_block.port('out_pol0');
  out_pol0_port.setType('UFix_18_0');
  out_pol1_port = this_block.port('out_pol1');
  out_pol1_port.setType('UFix_18_0');
  out_pol2_port = this_block.port('out_pol2');
  out_pol2_port.setType('UFix_18_0');
  out_pol3_port = this_block.port('out_pol3');
  out_pol3_port.setType('UFix_18_0');
  out_pol4_port = this_block.port('out_pol4');
  out_pol4_port.setType('UFix_18_0');
  out_pol5_port = this_block.port('out_pol5');
  out_pol5_port.setType('UFix_18_0');
  out_pol6_port = this_block.port('out_pol6');
  out_pol6_port.setType('UFix_18_0');
  out_pol7_port = this_block.port('out_pol7');
  out_pol7_port.setType('UFix_18_0');
  sync_out_port = this_block.port('sync_out');
  sync_out_port.setType('Bool');
  sync_out_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('pol0').width ~= 8);
      this_block.setError('Input data type for port "pol0" must have width=8.');
    end

    if (this_block.port('pol1').width ~= 8);
      this_block.setError('Input data type for port "pol1" must have width=8.');
    end

    if (this_block.port('pol2').width ~= 8);
      this_block.setError('Input data type for port "pol2" must have width=8.');
    end

    if (this_block.port('pol3').width ~= 8);
      this_block.setError('Input data type for port "pol3" must have width=8.');
    end

    if (this_block.port('pol4').width ~= 8);
      this_block.setError('Input data type for port "pol4" must have width=8.');
    end

    if (this_block.port('pol5').width ~= 8);
      this_block.setError('Input data type for port "pol5" must have width=8.');
    end

    if (this_block.port('pol6').width ~= 8);
      this_block.setError('Input data type for port "pol6" must have width=8.');
    end

    if (this_block.port('pol7').width ~= 8);
      this_block.setError('Input data type for port "pol7" must have width=8.');
    end

    if (this_block.port('sync').width ~= 1);
      this_block.setError('Input data type for port "sync" must have width=1.');
    end

    this_block.port('sync').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk_1','ce_1')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('/data1/dprice/leda512/bb/pfb_core.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

